server:
  port: 8081

# url de acesso do microservice de busca de endereco por cep
arantes:
  client:
    address:
      url: http://127.0.0.1:8082/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal